; Copyright ?Microsoft Corp.

[Theme]
; Windows 7 - IDS_THEME_DISPLAYNAME_AERO
DisplayName=All transparent

; Computer - SHIDI_SERVER
[CLSID\{20D04FE0-3AEA-1069-A2D8-08002B30309D}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-109

; UsersFiles - SHIDI_USERFILES
[CLSID\{59031A47-3F72-44A7-89C5-5595FE6B30EE}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-123

; Network - SHIDI_MYNETWORK
[CLSID\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}\DefaultIcon]
DefaultValue=%SystemRoot%\System32\imageres.dll,-25

; Recycle Bin - SHIDI_RECYCLERFULL SHIDI_RECYCLER
[CLSID\{645FF040-5081-101B-9F08-00AA002F954E}\DefaultIcon]
Full=%SystemRoot%\System32\imageres.dll,-54
Empty=%SystemRoot%\System32\imageres.dll,-55

[Control Panel\Cursors]
AppStarting=%SystemRoot%\Resources\Themes\AaeroA\cursors\AppStarting.ani
Arrow=%SystemRoot%\Resources\Themes\AaeroA\cursors\Arrow.cur
Crosshair=%SystemRoot%\Resources\Themes\AaeroA\cursors\Crosshair.cur
Hand=%SystemRoot%\Resources\Themes\AaeroA\cursors\Hand.cur
Help=%SystemRoot%\Resources\Themes\AaeroA\cursors\Help.cur
IBeam=%SystemRoot%\Resources\Themes\AaeroA\cursors\IBeam.cur
No=%SystemRoot%\Resources\Themes\AaeroA\cursors\NO.cur
NWPen=%SystemRoot%\Resources\Themes\AaeroA\cursors\NWPen.cur
SizeAll=%SystemRoot%\Resources\Themes\AaeroA\cursors\SizeAll.cur
SizeNESW=%SystemRoot%\Resources\Themes\AaeroA\cursors\SizeNESW.cur
SizeNS=%SystemRoot%\Resources\Themes\AaeroA\cursors\SizeNS.cur
SizeNWSE=%SystemRoot%\Resources\Themes\AaeroA\cursors\SizeNWSE.cur
SizeWE=%SystemRoot%\Resources\Themes\AaeroA\cursors\SizeWE.cur
UpArrow=%SystemRoot%\Resources\Themes\AaeroA\cursors\UpArrow.cur
Wait=%SystemRoot%\Resources\Themes\AaeroA\cursors\Wait.ani
DefaultValue=一见倾心
Link=

[Control Panel\Desktop]
Wallpaper=%SystemRoot%\resources\Themes\AaeroA\wallpapers\001.jpg
TileWallpaper=0
WallpaperStyle=10
Pattern=

[VisualStyles]
Path=%SystemRoot%\resources\Themes\AaeroA\AaeroA.msstyles
ColorStyle=NormalColor
Size=NormalSize
ColorizationColor=0X1AFAFAFA
Transparency=1
Composition=1
VisualStyleVersion=10

[boot]
SCRNSAVE.EXE=

[MasterThemeSelector]
MTSM=DABJDKT

[Sounds]
; IDS_SCHEME_DEFAULT
SchemeName=釘宮理恵

[Sounds.A]
SchemeName=釘宮理恵
[Sounds.W]
SchemeName=+kdhbrnQGYHU-
[AppEvents\Schemes\Apps\.Default\AppGPFault]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\焦っちゃダメですよぅ.wav
[AppEvents\Schemes\Apps\.Default\ChangeTheme]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\お兄ちゃんだーい好き！.wav
[AppEvents\Schemes\Apps\.Default\SystemExclamation]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\オーケー？.wav
[AppEvents\Schemes\Apps\.Default\SystemHand]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\ポーン.wav
[AppEvents\Schemes\Apps\.Default\WindowsLogoff]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\もう．．．．．．眠いれす．．．．．．.wav
[AppEvents\Schemes\Apps\.Default\WindowsUAC]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\うにゅ？.wav
[AppEvents\Schemes\Apps\Explorer\EmptyRecycleBin]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\キスって気持ちイイ？.wav
[AppEvents\Schemes\Apps\.Default\.Default]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\うにゅ？.wav
[AppEvents\Schemes\Apps\.Default\CriticalBatteryAlarm]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\ムッフッフ～.wav
[AppEvents\Schemes\Apps\.Default\DeviceConnect]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\はふ～ん.wav
[AppEvents\Schemes\Apps\.Default\DeviceDisconnect]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\う～イジイジ．．．．．．.wav
[AppEvents\Schemes\Apps\.Default\DeviceFail]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\う～泣いちゃうぞ～！.wav
[AppEvents\Schemes\Apps\.Default\FaxBeep]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\にゃにゃ！これってウィルスぅ～！？.wav
[AppEvents\Schemes\Apps\.Default\LowBatteryAlarm]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\もぉ～、ヘンなところクリックしないでよぉ～.wav
[AppEvents\Schemes\Apps\.Default\MailBeep]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\にゃにゃ！これってウィルスぅ～！？.wav
[AppEvents\Schemes\Apps\.Default\PrintComplete]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\さぁた～んと召し上がれ.wav
[AppEvents\Schemes\Apps\.Default\SystemAsterisk]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\はふ～ん.wav
[AppEvents\Schemes\Apps\.Default\SystemExit]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\退出win.wav
[AppEvents\Schemes\Apps\.Default\SystemNotification]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\ダンナさま～！.wav
[AppEvents\Schemes\Apps\.Default\WindowsLogon]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\启动win.wav
[AppEvents\Schemes\Apps\Explorer\BlockedPopup]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\うにゅ？.wav
[AppEvents\Schemes\Apps\sapisvr\HubSleepSound]
DefaultValue=%SystemRoot%\Resources\Themes\AaeroA\Media\もっと、甘えちゃおうかな？.wav

[Theme.A]
[Theme.W]
DisplayName=+ZypP3VtYdoROO5iY-

[Slideshow]
Interval=1800000
Shuffle=0
ImagesRootPath=%SystemRoot%\Resources\Themes\AaeroA\wallpapers
Item0Path=%SystemRoot%\Resources\Themes\AaeroA\wallpapers\001.jpg
Item1Path=%SystemRoot%\Resources\Themes\AaeroA\wallpapers\002.jpg
Item2Path=%SystemRoot%\Resources\Themes\AaeroA\wallpapers\003.jpg
Item3Path=%SystemRoot%\Resources\Themes\AaeroA\wallpapers\004.jpg

